stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - master
    - fixPipeline
  tags:
    - nodejs
  script:
    - npm install
    - npm run build:PROD
  artifacts:
    paths:
      - dist

test:
  stage: test
  only:
    - master
    - fixPipeline
  tags:
    - nodejs
  script:
    - npm install
    - npm test

deploy:
  stage: deploy
  only:
    - master
    - fixPipeline
  tags:
    - rsync
  dependencies:
    - build
  script:
    - chmod -R a+rX,ug+w .
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh
    - ssh-keyscan "$STAGING_BACKEND_URL" >> ~/.ssh/known_hosts    
    - ssh-add <(echo "$STAGING_SSH_PRIVATE_KEY")
    - rsync -rltgoDqv --delete -e "ssh" dist/* "$STAGING_BACKEND_SSH_URL"

