stages:
  - install
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install_node_modules:
  stage: install
  tags:
    - nodejs
  script:
  - npm install

ts_lint:
  stage: test
  tags:
    - nodejs
  script:
    - npm install
    - node_modules/tslint/bin/tslint -c tslint.json -p tsconfig.json

npm_test:
  stage: test
  tags:
    - nodejs
  script:
    - npm test

build:
  stage: build
  only:
    - master
  tags:
    - nodejs
  script:
    - npm install
    - export NODE_ENV='production'
    - export ARSNOVA_CLICK_BACKEND_PORT_INTERNAL='3000'
    - export ARSNOVA_CLICK_BACKEND_ROUTE_PREFIX='/backend'
    - npm run build:PROD
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  only:
    - master
  tags:
    - rsync
  dependencies:
    - build
  script:
    - chmod -R a+rX,ug+w .
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh
    - ssh-keyscan "$STAGING_BACKEND_URL" >> ~/.ssh/known_hosts    
    - ssh-add <(echo "$STAGING_SSH_PRIVATE_KEY")
    - rsync -rltgoDqv --delete -e "ssh" dist/* "$STAGING_BACKEND_SSH_URL"
    - ssh $NEW_PRODUCTION_SSH 'touch /home/arsnova/arsnova.click-v2/backend/deploy.touch'

