version: '3.7'

services:
  node:
    image: arsnova/arsnova-click-backend:2.0.0
    container_name: arsnova-click-backend
    hostname: arsnova-click-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3010:3010
    networks:
      - app-tier
    env_file: arsnova-click.env
    depends_on:
      - rabbitmq
      - mongodb
  rabbitmq:
    image: bitnami/rabbitmq:3.7.17
    container_name: arsnova-click-backend-rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 15674:15674
      - 5672:5672
    networks:
      - app-tier
    env_file: rabbitmq.env
    volumes:
      - rabbitmq:/bitnami
      - ./rabbitmq-plugins.txt:/opt/bitnami/rabbitmq/etc/rabbitmq/enabled_plugins
  mongodb:
    image: mongo:4.0.5
    container_name: arsnova-click-backend-mongodb
    hostname: mongodb
    ports:
      - 27017:27017
    networks:
      - app-tier
    env_file: mongo.env
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb:/data/db

networks:
  app-tier:
    driver: bridge

volumes:
  mongodb:
    driver: local
  rabbitmq:
    driver: local
