version: '3.7'
services:
  master:
    image: arsnova/arsnova-click-backend:2.0.0
    hostname: arsnova-click-backend
    container_name: arsnova-click-backend-master
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        CHROMIUM_PATH: "/usr/bin/chromium-browser"
    ports:
      - 3010:3010
    networks:
      - app-tier
    env_file: arsnova-click.env
    depends_on:
      - rabbitmq
      - mongodb
  staging:
    image: arsnova/arsnova-click-backend:2.0.0-staging
    hostname: arsnova-click-backend
    container_name: arsnova-click-backend-staging
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        CHROMIUM_PATH: "/usr/bin/chromium-browser"
    ports:
      - 3020:3010
    networks:
      - app-tier
    env_file: arsnova-click-staging.env
    depends_on:
      - rabbitmq
      - mongodb
  beta:
    image: arsnova/arsnova-click-backend:2.0.0-beta
    hostname: arsnova-click-backend
    container_name: arsnova-click-backend-beta
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        CHROMIUM_PATH: "/usr/bin/chromium-browser"
    ports:
      - 3030:3010
    networks:
      - app-tier
    env_file: arsnova-click-beta.env
    depends_on:
      - rabbitmq
      - mongodb
  rabbitmq:
    image: bitnami/rabbitmq:3.7.17
    container_name: arsnova-click-backend-rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 15674:15674
      - 5672:5672
    networks:
      - app-tier
    env_file: rabbitmq.env
    volumes:
      - rabbitmq:/bitnami
      - ./rabbitmq-plugins.txt:/opt/bitnami/rabbitmq/etc/rabbitmq/enabled_plugins
  mongodb:
    image: mongo:4.0.5
    container_name: arsnova-click-backend-mongodb
    hostname: mongodb
    ports:
      - 27017:27017
    networks:
      - app-tier
    env_file: mongo.env
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb:/data/db

networks:
  app-tier:
    driver: bridge

volumes:
  mongodb:
    driver: local
  rabbitmq:
    driver: local
